version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels: [dependencies, bot, github_actions]
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    labels: [dependencies, bot, dart]
    commit-message:
      prefix: fix
      prefix-development: chore
    allow:
      dependency-type: direct
    # Configure groups for dependencies.
    groups:
      flutter-app:
        dependency-type: production
      flutter-dev:
        dependency-type: development
    # Leave the constraint if the original constraint allows the new version, otherwise, bump the constraint.
    versioning-strategy: increase-if-necessary
