name: calculator
description: A Very Good Project created by Very Good CLI.
version: 1.0.1+1
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^9.2.0
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.11.2
  math_expressions: ^3.1.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  mockito: ^5.6.3
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

# https://github.com/frencojobs/derry
# `dart pub global activate derry`
scripts: derry.yaml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: SFProDisplay
      # https://developer.apple.com/fonts/
      fonts:
        - asset: assets/fonts/SFProDisplay_Bold.otf
          weight: 700
        - asset: assets/fonts/SFProDisplay_Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay_Regular.otf
          weight: 400
